---
env:
  browser: true
  es2021: true
  node: true
  es6: true
  jest: true

extends:
  - eslint:recommended
  - airbnb-base
  - prettier

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - prettier

rules:
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  consistent-return: [0, { 'treatUndefinedAsUnspecified': true }]
