env:
  browser: true
  es2021: true
  jest: true

extends:
  - airbnb-base
  - prettier

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - prettier

rules:
  no-console: 0
   import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
