name: Setup and Install
description: Setup workflow for the project and install all dependencies

runs:
  using: composite
  steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      id: install
      run: make install
