name: GenDiff Check
# Events
on:
  push:
    branches:
      - '**'
  pull_request:
env:
  CI: true
jobs:
  # Install
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: make install
  # Linting
  lint:
    needs: [install]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Linting
        run: make lint
  # Testing  using Jest
  jest:
    needs: [install, lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Testing
        run: make test
  # CodeClimate Test Coverage job
  coverage:
    needs: [install, lint, jest]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: CodeClimate Test Coverage
        uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: $CODECLIMATE_COVERAGE_ID
        with:
          coverageCommand: make test-coverage
